/**
 * Long-Form Genre Templates
 *
 * Ready-to-use templates for each of the 8 genres
 */

import {
  LongFormGenre,
  LongFormStructure,
  LongFormScene,
  FactCard,
} from '../../types-longform';

/**
 * 1. Historical Reconstruction Template
 * Example: Fall of the Roman Empire
 */
export const createHistoricalReconstructionTemplate = (): LongFormStructure => ({
  genre: LongFormGenre.HISTORICAL_RECONSTRUCTION,
  totalDuration: 8,
  title: 'Fall of the Roman Empire: A Historical Reconstruction',
  description: 'A journey through time to the golden age and collapse of one of history\'s greatest empires',
  scenes: [
    {
      id: 1,
      title: 'The Golden Age',
      duration: 80,
      pieceCount: 400,
      imagePrompt: 'Ancient Roman forum at golden hour, marble columns, bustling marketplace, citizens in togas, hyperrealistic',
      storyBeat: 'In 117 AD, the Roman Empire reached its greatest extent',
      musicMood: 'Epic Glory',
      factCards: [
        {
          timestamp: 15,
          type: 'statistic',
          content: '🏛️ Rome ruled over 5 million square kilometers',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 50,
          type: 'fact',
          content: '⚔️ The Roman army had 30 legions (150,000 soldiers)',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'fade',
    },
    {
      id: 2,
      title: 'First Signs of Trouble',
      duration: 90,
      pieceCount: 600,
      imagePrompt: 'Roman military camp under stormy sky, barbarian tribes in distance, tension, dramatic lighting',
      storyBeat: 'But from 235 AD, the crisis began',
      musicMood: 'Building Tension',
      factCards: [
        {
          timestamp: 20,
          type: 'question',
          content: '❓ What caused the fall of Rome?',
          duration: 3,
          position: 'center',
          animation: 'pop',
        },
        {
          timestamp: 60,
          type: 'fact',
          content: '📉 In 50 years, 26 emperors rose to power',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
      ],
      transitionType: 'puzzle-wipe',
    },
    {
      id: 3,
      title: 'Barbarian Invasions',
      duration: 100,
      pieceCount: 800,
      imagePrompt: 'Barbarian invasion, Rome under siege, burning buildings, chaos, epic battle scene',
      storyBeat: 'Germanic and Gothic tribes attacked the empire\'s borders',
      musicMood: 'Intense Battle',
      factCards: [
        {
          timestamp: 15,
          type: 'fact',
          content: '⚔️ Battle of Adrianople (378 AD): Rome\'s great defeat',
          duration: 4,
          position: 'top',
          animation: 'slide',
        },
        {
          timestamp: 50,
          type: 'countdown',
          content: '⏳ 96 years until the final fall',
          duration: 3,
          position: 'bottom',
          animation: 'fade',
        },
        {
          timestamp: 80,
          type: 'quote',
          content: '"Rome was not destroyed by barbarians, it rotted from within" - Historian',
          duration: 5,
          position: 'center',
          animation: 'fade',
        },
      ],
      transitionType: 'hard-cut',
    },
    {
      id: 4,
      title: 'Empire Divided',
      duration: 70,
      pieceCount: 500,
      imagePrompt: 'Split Roman Empire map, Eastern and Western divisions, political intrigue, dramatic contrast',
      storyBeat: 'In 395 AD, the Empire was divided into Eastern and Western parts',
      musicMood: 'Melancholic',
      factCards: [
        {
          timestamp: 15,
          type: 'fact',
          content: '🗺️ Western Rome: Weak | Eastern Rome (Byzantium): Strong',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 50,
          type: 'statistic',
          content: '📊 Western Rome lasted only 81 more years',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'zoom',
    },
    {
      id: 5,
      title: 'The Final Fall',
      duration: 80,
      pieceCount: 600,
      imagePrompt: 'Fall of Rome 476 AD, barbarian king Odoacer deposing last emperor, ruins, sunset over fallen empire',
      storyBeat: 'In 476 AD, the last Western Roman Emperor was deposed',
      musicMood: 'Tragic Fall',
      factCards: [
        {
          timestamp: 15,
          type: 'fact',
          content: '👑 Romulus Augustulus: The last emperor (16 years old)',
          duration: 5,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 50,
          type: 'statistic',
          content: '📅 1,229 years had passed since Rome\'s founding',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'fade',
    },
    {
      id: 6,
      title: 'Eternal Legacy',
      duration: 60,
      pieceCount: 400,
      imagePrompt: 'Modern Rome, Colosseum, ancient ruins merged with modern city, legacy of Rome, cinematic',
      storyBeat: 'But Rome\'s legacy never died: law, language, architecture, and civilization',
      musicMood: 'Hopeful Legacy',
      factCards: [
        {
          timestamp: 15,
          type: 'fact',
          content: '🏛️ Rome\'s Legacy: Democracy, Law, Language, Architecture',
          duration: 5,
          position: 'center',
          animation: 'pop',
        },
        {
          timestamp: 40,
          type: 'quote',
          content: '"All roads lead to Rome"',
          duration: 3,
          position: 'bottom',
          animation: 'fade',
        },
      ],
      transitionType: 'fade',
    },
  ],
  musicStrategy: {
    type: 'dynamic-multi-track',
    tracks: [
      { sceneId: 1, mood: 'Epic Glory', intensity: 7, transitionType: 'fade' },
      { sceneId: 2, mood: 'Building Tension', intensity: 5, transitionType: 'crossfade', crossfadeDuration: 4 },
      { sceneId: 3, mood: 'Intense Battle', intensity: 9, transitionType: 'hard-cut' },
      { sceneId: 4, mood: 'Melancholic', intensity: 4, transitionType: 'crossfade', crossfadeDuration: 5 },
      { sceneId: 5, mood: 'Tragic Fall', intensity: 8, transitionType: 'crossfade', crossfadeDuration: 4 },
      { sceneId: 6, mood: 'Hopeful Legacy', intensity: 6, transitionType: 'fade' },
    ],
  },
  retentionHooks: {
    progressBar: {
      enabled: true,
      position: 'bottom',
      style: 'chapter-count',
    },
    factCardFrequency: 25,
    chapterTitles: true,
    transitionAnimations: true,
  },
});

/**
 * 2. Scientific Deep-Dive Template
 * Example: From Galaxy to DNA
 */
export const createScientificDeepdiveTemplate = (): LongFormStructure => ({
  genre: LongFormGenre.SCIENTIFIC_DEEPDIVE,
  totalDuration: 8,
  title: 'From Galaxy to DNA: Journey to the Depths of Existence',
  description: 'An amazing scientific journey from the largest structure to the smallest unit of life',
  scenes: [
    {
      id: 1,
      title: 'The Milky Way Galaxy',
      duration: 90,
      pieceCount: 500,
      imagePrompt: 'Milky Way galaxy from space, billions of stars, cosmic beauty, ultra detailed, scientific visualization',
      storyBeat: 'Our galaxy contains 200-400 billion stars',
      musicMood: 'Cosmic Wonder',
      factCards: [
        {
          timestamp: 20,
          type: 'statistic',
          content: '🌌 Galaxy diameter: 100,000 light-years',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 60,
          type: 'fact',
          content: '⭐ The Sun is just one of billions of stars',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'zoom',
    },
    {
      id: 2,
      title: 'The Solar System',
      duration: 90,
      pieceCount: 600,
      imagePrompt: 'Solar system with all planets, asteroid belt, detailed planetary textures, scientific accuracy',
      storyBeat: 'Our solar system: 8 planets, 5 dwarf planets, and billions of asteroids',
      musicMood: 'Exploration',
      factCards: [
        {
          timestamp: 15,
          type: 'question',
          content: '❓ Why is Pluto no longer a planet?',
          duration: 3,
          position: 'center',
          animation: 'pop',
        },
        {
          timestamp: 60,
          type: 'fact',
          content: '🪐 Jupiter could fit 1,300 Earths inside it',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
      ],
      transitionType: 'zoom',
    },
    {
      id: 3,
      title: 'Planet Earth',
      duration: 100,
      pieceCount: 800,
      imagePrompt: 'Earth from space, blue marble, clouds, continents, oceans, breathtaking view, NASA quality',
      storyBeat: 'The only world where we know life exists',
      musicMood: 'Earth Beauty',
      factCards: [
        {
          timestamp: 20,
          type: 'statistic',
          content: '🌍 Age of Earth: 4.5 billion years',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 60,
          type: 'fact',
          content: '💧 71% of Earth\'s surface is ocean',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'zoom',
    },
    {
      id: 4,
      title: 'The Human Body',
      duration: 80,
      pieceCount: 700,
      imagePrompt: 'Human anatomy, organs, circulatory system, scientific illustration, detailed, educational',
      storyBeat: 'The human body: A complex machine of 37 trillion cells',
      musicMood: 'Biological Wonder',
      factCards: [
        {
          timestamp: 15,
          type: 'statistic',
          content: '🫀 The heart beats 2.5 billion times in a lifetime',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 55,
          type: 'fact',
          content: '🧠 The human brain has 86 billion neurons',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'zoom',
    },
    {
      id: 5,
      title: 'The Cell',
      duration: 90,
      pieceCount: 900,
      imagePrompt: 'Human cell cross-section, nucleus, mitochondria, organelles, scientific accuracy, microscopic view',
      storyBeat: 'The cell: The fundamental unit of life',
      musicMood: 'Microscopic Discovery',
      factCards: [
        {
          timestamp: 20,
          type: 'fact',
          content: '🔬 Mitochondria: The powerhouse of the cell',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 60,
          type: 'question',
          content: '❓ What does the cell nucleus do?',
          duration: 3,
          position: 'center',
          animation: 'pop',
        },
      ],
      transitionType: 'zoom',
    },
    {
      id: 6,
      title: 'DNA: The Blueprint of Life',
      duration: 70,
      pieceCount: 600,
      imagePrompt: 'DNA double helix, genetic code, colorful base pairs, scientific beauty, ultra detailed',
      storyBeat: 'DNA: A book that tells the story of all living things',
      musicMood: 'Genetic Code',
      factCards: [
        {
          timestamp: 15,
          type: 'statistic',
          content: '🧬 Human DNA has 3 billion base pairs',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 45,
          type: 'fact',
          content: '🔗 If you stretched out the DNA in a cell, it would be 2 meters long!',
          duration: 5,
          position: 'center',
          animation: 'pop',
        },
      ],
      transitionType: 'fade',
    },
  ],
  musicStrategy: {
    type: 'single-track',
    tracks: [
      { sceneId: 1, mood: 'Cosmic Documentary', intensity: 6, transitionType: 'fade' },
    ],
  },
  retentionHooks: {
    progressBar: {
      enabled: true,
      position: 'top',
      style: 'percentage',
    },
    factCardFrequency: 20,
    chapterTitles: true,
    transitionAnimations: true,
  },
});

/**
 * 3. Mystery Reveal Template
 * Example: The Bermuda Triangle Mystery
 */
export const createMysteryRevealTemplate = (): LongFormStructure => ({
  genre: LongFormGenre.MYSTERY_REVEAL,
  totalDuration: 8,
  title: 'The Bermuda Triangle: Truth Behind the Mystery',
  description: 'Do ships and planes really disappear in the Bermuda Triangle?',
  scenes: [
    {
      id: 1,
      title: 'The Mysterious Event',
      duration: 70,
      pieceCount: 400,
      imagePrompt: 'Bermuda Triangle from above, stormy ocean, mysterious fog, disappearing plane, cinematic',
      storyBeat: 'December 1945: Five U.S. Navy planes vanished',
      musicMood: 'Suspenseful Mystery',
      factCards: [
        {
          timestamp: 15,
          type: 'fact',
          content: '✈️ Flight 19: 5 planes, 14 pilots, all vanished',
          duration: 5,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 50,
          type: 'question',
          content: '❓ What happened?',
          duration: 3,
          position: 'center',
          animation: 'pop',
        },
      ],
      transitionType: 'fade',
    },
    {
      id: 2,
      title: 'Theory 1: Rogue Waves',
      duration: 90,
      pieceCount: 600,
      imagePrompt: 'Rogue wave, massive ocean wave towering over ship, dramatic, realistic, terrifying',
      storyBeat: 'Are giant rogue waves responsible?',
      musicMood: 'Tension',
      factCards: [
        {
          timestamp: 20,
          type: 'statistic',
          content: '🌊 Wave height: Up to 30 meters (height of a 10-story building)',
          duration: 5,
          position: 'top',
          animation: 'slide',
        },
        {
          timestamp: 65,
          type: 'fact',
          content: '⚠️ Rogue waves can appear suddenly',
          duration: 4,
          position: 'bottom',
          animation: 'fade',
        },
      ],
      transitionType: 'puzzle-wipe',
    },
    {
      id: 3,
      title: 'Theory 2: Magnetic Field',
      duration: 90,
      pieceCount: 700,
      imagePrompt: 'Magnetic anomaly, compass going haywire, electromagnetic interference, scientific visualization',
      storyBeat: 'Does the magnetic field mislead compasses?',
      musicMood: 'Scientific Investigation',
      factCards: [
        {
          timestamp: 20,
          type: 'fact',
          content: '🧭 Compasses behave unusually in this area',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 65,
          type: 'statistic',
          content: '📊 But research shows this effect is negligible',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'hard-cut',
    },
    {
      id: 4,
      title: 'Theory 3: Methane from the Deep',
      duration: 80,
      pieceCount: 600,
      imagePrompt: 'Methane bubbles rising from ocean floor, underwater explosion, ship sinking, scientific accuracy',
      storyBeat: 'Does methane gas from the seabed sink ships?',
      musicMood: 'Revelation',
      factCards: [
        {
          timestamp: 20,
          type: 'fact',
          content: '💨 Methane bubbles can reduce water density',
          duration: 5,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 60,
          type: 'statistic',
          content: '🔬 Experiments have confirmed this theory',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'zoom',
    },
    {
      id: 5,
      title: 'The Truth',
      duration: 90,
      pieceCount: 700,
      imagePrompt: 'Bermuda Triangle map with shipping lanes, busy ocean traffic, normal maritime activity',
      storyBeat: 'The truth: The Bermuda Triangle is no more dangerous than other areas!',
      musicMood: 'Truth Revealed',
      factCards: [
        {
          timestamp: 20,
          type: 'statistic',
          content: '📊 Accident rates in the Bermuda Triangle are normal',
          duration: 5,
          position: 'center',
          animation: 'pop',
        },
        {
          timestamp: 60,
          type: 'fact',
          content: '✅ Marine insurance: No rate increase',
          duration: 4,
          position: 'bottom',
          animation: 'fade',
        },
      ],
      transitionType: 'fade',
    },
    {
      id: 6,
      title: 'Mystery Solved',
      duration: 60,
      pieceCount: 400,
      imagePrompt: 'Calm Bermuda Triangle, beautiful sunset, peaceful ocean, debunked myth, closure',
      storyBeat: 'The Bermuda Triangle legend: A mix of media exaggeration and human error',
      musicMood: 'Peaceful Conclusion',
      factCards: [
        {
          timestamp: 15,
          type: 'quote',
          content: '"The truth is often simpler than the legend"',
          duration: 4,
          position: 'center',
          animation: 'fade',
        },
        {
          timestamp: 45,
          type: 'fact',
          content: '🌍 Thousands of ships and planes pass safely every day',
          duration: 5,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'fade',
    },
  ],
  musicStrategy: {
    type: 'single-track',
    tracks: [
      { sceneId: 1, mood: 'Mystery Documentary', intensity: 7, transitionType: 'fade' },
    ],
  },
  retentionHooks: {
    progressBar: {
      enabled: true,
      position: 'bottom',
      style: 'time-remaining',
    },
    factCardFrequency: 20,
    chapterTitles: true,
    transitionAnimations: true,
  },
});

/**
 * 4. Geographic Journey Template
 * Example: Seven Wonders of the World
 */
export const createGeographicJourneyTemplate = (): LongFormStructure => ({
  genre: LongFormGenre.GEOGRAPHIC_JOURNEY,
  totalDuration: 8,
  title: 'New Seven Wonders: A Journey Around the World',
  description: 'A virtual visit to seven architectural and natural masterpieces',
  scenes: [
    {
      id: 1,
      title: 'The Great Wall of China',
      duration: 70,
      pieceCount: 500,
      imagePrompt: 'Great Wall of China winding through misty mountains, aerial view, sunrise, majestic, cinematic',
      storyBeat: 'The longest man-made structure: 21,000 kilometers',
      musicMood: 'Asian Epic',
      factCards: [
        {
          timestamp: 15,
          type: 'statistic',
          content: '🏯 Built: From 2,700 to 400 years ago',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 50,
          type: 'fact',
          content: '👷 Millions of workers participated in its construction',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'fade',
    },
    {
      id: 2,
      title: 'Christ the Redeemer',
      duration: 65,
      pieceCount: 400,
      imagePrompt: 'Christ the Redeemer statue Rio de Janeiro, sunset, dramatic clouds, iconic pose, breathtaking',
      storyBeat: 'Rio de Janeiro, Brazil: A symbol of hope and open arms',
      musicMood: 'Latin Spirit',
      factCards: [
        {
          timestamp: 15,
          type: 'statistic',
          content: '🗿 Height: 30 meters | Weight: 635 tons',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 45,
          type: 'fact',
          content: '⚡ Lightning strikes it several times a year',
          duration: 5,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'zoom',
    },
    {
      id: 3,
      title: 'Machu Picchu',
      duration: 85,
      pieceCount: 700,
      imagePrompt: 'Machu Picchu ancient Inca citadel in clouds, mountain peaks, mystical atmosphere, UNESCO heritage',
      storyBeat: 'The Lost City of the Incas at 2,430 meters elevation',
      musicMood: 'Andean Mystery',
      factCards: [
        {
          timestamp: 20,
          type: 'fact',
          content: '🏔️ Built in the 15th century AD',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 60,
          type: 'question',
          content: '❓ How did the Incas move such massive stones?',
          duration: 4,
          position: 'center',
          animation: 'pop',
        },
      ],
      transitionType: 'puzzle-wipe',
    },
    {
      id: 4,
      title: 'The Colosseum of Rome',
      duration: 80,
      pieceCount: 600,
      imagePrompt: 'Colosseum Rome at golden hour, ancient amphitheater, gladiator arena, historical marvel',
      storyBeat: 'Rome\'s magnificent amphitheater: Witness to gladiator battles',
      musicMood: 'Roman Glory',
      factCards: [
        {
          timestamp: 15,
          type: 'statistic',
          content: '🏛️ Capacity: 50,000 spectators',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 55,
          type: 'fact',
          content: '⚔️ Naval battles were also held here',
          duration: 5,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'hard-cut',
    },
    {
      id: 5,
      title: 'The Taj Mahal',
      duration: 80,
      pieceCount: 650,
      imagePrompt: 'Taj Mahal at dawn, white marble reflecting in pool, symmetrical beauty, Islamic architecture masterpiece',
      storyBeat: 'A tomb of love: A masterpiece of Indian Islamic architecture',
      musicMood: 'Indian Serenity',
      factCards: [
        {
          timestamp: 20,
          type: 'quote',
          content: '"Marble that tells a story of love"',
          duration: 4,
          position: 'center',
          animation: 'fade',
        },
        {
          timestamp: 60,
          type: 'statistic',
          content: '💎 22 years to build | 20,000 workers',
          duration: 4,
          position: 'top',
          animation: 'slide',
        },
      ],
      transitionType: 'fade',
    },
    {
      id: 6,
      title: 'Chichen Itza',
      duration: 70,
      pieceCount: 550,
      imagePrompt: 'Chichen Itza El Castillo pyramid Mexico, Maya calendar temple, archaeological wonder, dramatic sky',
      storyBeat: 'The Pyramid of Kukulcan: The Mayan solar calendar',
      musicMood: 'Maya Wonder',
      factCards: [
        {
          timestamp: 15,
          type: 'fact',
          content: '🔺 91 steps on each side + 1 top step = 365 days',
          duration: 5,
          position: 'top',
          animation: 'pop',
        },
        {
          timestamp: 50,
          type: 'statistic',
          content: '🌅 At the spring equinox, a snake shadow appears',
          duration: 5,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'zoom',
    },
    {
      id: 7,
      title: 'Petra',
      duration: 70,
      pieceCount: 500,
      imagePrompt: 'Petra Jordan, Al-Khazneh treasury carved in red rock, ancient Nabataean city, rose-red city',
      storyBeat: 'The Rock City: Capital of the Nabataeans in the heart of the desert',
      musicMood: 'Desert Majesty',
      factCards: [
        {
          timestamp: 15,
          type: 'fact',
          content: '🏜️ Rediscovered in 1812',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 50,
          type: 'quote',
          content: '"A rose-red city half as old as time" - English poem',
          duration: 5,
          position: 'center',
          animation: 'fade',
        },
      ],
      transitionType: 'fade',
    },
  ],
  musicStrategy: {
    type: 'dynamic-multi-track',
    tracks: [
      { sceneId: 1, mood: 'Asian Epic', intensity: 6, transitionType: 'crossfade', crossfadeDuration: 4 },
      { sceneId: 2, mood: 'Latin Spirit', intensity: 7, transitionType: 'crossfade', crossfadeDuration: 4 },
      { sceneId: 3, mood: 'Andean Mystery', intensity: 5, transitionType: 'crossfade', crossfadeDuration: 4 },
      { sceneId: 4, mood: 'Roman Glory', intensity: 8, transitionType: 'crossfade', crossfadeDuration: 4 },
      { sceneId: 5, mood: 'Indian Serenity', intensity: 5, transitionType: 'crossfade', crossfadeDuration: 5 },
      { sceneId: 6, mood: 'Maya Wonder', intensity: 6, transitionType: 'crossfade', crossfadeDuration: 4 },
      { sceneId: 7, mood: 'Desert Majesty', intensity: 7, transitionType: 'fade' },
    ],
  },
  retentionHooks: {
    progressBar: {
      enabled: true,
      position: 'top',
      style: 'chapter-count',
    },
    factCardFrequency: 30,
    chapterTitles: true,
    transitionAnimations: true,
  },
});

/**
 * 5. Art Evolution Template
 * Example: History of Painting from Caves to Digital
 */
export const createArtEvolutionTemplate = (): LongFormStructure => ({
  genre: LongFormGenre.ART_EVOLUTION,
  totalDuration: 8,
  title: 'Evolution of Painting: From Ancient Caves to Digital Art',
  description: 'A 40,000-year journey through the history of human painting',
  scenes: [
    {
      id: 1,
      title: 'Cave Paintings',
      duration: 70,
      pieceCount: 400,
      imagePrompt: 'Cave painting prehistoric art, bison and horses on rock wall, Lascaux style, ancient humanity',
      storyBeat: '40,000 years ago: The first human artists',
      musicMood: 'Primal Drums',
      factCards: [
        {
          timestamp: 15,
          type: 'statistic',
          content: '🦬 Lascaux Cave: 17,000 years old',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 50,
          type: 'fact',
          content: '🎨 Pigments: Iron oxide, charcoal, chalk',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'fade',
    },
    {
      id: 2,
      title: 'Ancient Egyptian Art',
      duration: 80,
      pieceCount: 600,
      imagePrompt: 'Ancient Egyptian art, hieroglyphics, profile figures, papyrus paintings, golden age, detailed',
      storyBeat: 'Ancient Egypt: Art for eternity',
      musicMood: 'Egyptian Mystique',
      factCards: [
        {
          timestamp: 20,
          type: 'fact',
          content: '👁️ Frontality rule: Profile face, front-facing eye',
          duration: 5,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 60,
          type: 'statistic',
          content: '📜 Egyptian art remained almost unchanged for 3,000 years',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'zoom',
    },
    {
      id: 3,
      title: 'Renaissance: The Art Revolution',
      duration: 100,
      pieceCount: 800,
      imagePrompt: 'Renaissance masterpiece, Mona Lisa style, sfumato technique, Leonardo da Vinci quality, realistic portrait',
      storyBeat: '15th-16th century: Return to realism and humanism',
      musicMood: 'Renaissance Beauty',
      factCards: [
        {
          timestamp: 25,
          type: 'quote',
          content: '"Art is science made visible" - Leonardo da Vinci',
          duration: 5,
          position: 'center',
          animation: 'fade',
        },
        {
          timestamp: 70,
          type: 'fact',
          content: '🎨 Innovation: Perspective, lighting, precise anatomy',
          duration: 5,
          position: 'top',
          animation: 'slide',
        },
      ],
      transitionType: 'puzzle-wipe',
    },
    {
      id: 4,
      title: 'Impressionism: Capture the Moment',
      duration: 90,
      pieceCount: 700,
      imagePrompt: 'Impressionist painting, water lilies, broken brushstrokes, light and color, Monet style, dreamy',
      storyBeat: '19th century: Artists went outdoors',
      musicMood: 'French Impressionism',
      factCards: [
        {
          timestamp: 20,
          type: 'fact',
          content: '🌅 Claude Monet: 250 paintings of water lilies',
          duration: 5,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 65,
          type: 'statistic',
          content: '🎨 Technique: Visible brushstrokes, pure color',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'fade',
    },
    {
      id: 5,
      title: 'Cubism: Shattered Reality',
      duration: 80,
      pieceCount: 600,
      imagePrompt: 'Cubist painting, geometric shapes, multiple perspectives, Picasso style, abstract fragmented reality',
      storyBeat: '20th century: Picasso and Braque shattered reality',
      musicMood: 'Modern Jazz',
      factCards: [
        {
          timestamp: 15,
          type: 'question',
          content: '❓ Why show multiple viewpoints in one painting?',
          duration: 4,
          position: 'center',
          animation: 'pop',
        },
        {
          timestamp: 55,
          type: 'fact',
          content: '🎨 Picasso: "Art is a lie that tells the truth"',
          duration: 5,
          position: 'top',
          animation: 'fade',
        },
      ],
      transitionType: 'hard-cut',
    },
    {
      id: 6,
      title: 'Abstract Art: Absolute Freedom',
      duration: 70,
      pieceCount: 500,
      imagePrompt: 'Abstract expressionism, Jackson Pollock drip painting, color explosion, emotional chaos, pure emotion',
      storyBeat: '1950: Art without subject, only feeling',
      musicMood: 'Avant-garde',
      factCards: [
        {
          timestamp: 15,
          type: 'fact',
          content: '🎨 Jackson Pollock: Drip technique',
          duration: 4,
          position: 'top',
          animation: 'slide',
        },
        {
          timestamp: 50,
          type: 'quote',
          content: '"When I am in my painting, I am not aware of what I am doing"',
          duration: 5,
          position: 'center',
          animation: 'fade',
        },
      ],
      transitionType: 'zoom',
    },
    {
      id: 7,
      title: 'Digital Art: The New Frontier',
      duration: 70,
      pieceCount: 900,
      imagePrompt: 'Digital art NFT, futuristic artwork, AI-generated art, glitch art, cyberpunk aesthetic, modern technology',
      storyBeat: '21st century: Art in the digital world and NFTs',
      musicMood: 'Electronic Future',
      factCards: [
        {
          timestamp: 15,
          type: 'statistic',
          content: '💰 First major NFT: Sold for $69 million',
          duration: 5,
          position: 'top',
          animation: 'pop',
        },
        {
          timestamp: 50,
          type: 'fact',
          content: '🤖 AI can now create art',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'fade',
    },
  ],
  musicStrategy: {
    type: 'dynamic-multi-track',
    tracks: [
      { sceneId: 1, mood: 'Primal Drums', intensity: 4, transitionType: 'fade' },
      { sceneId: 2, mood: 'Egyptian Mystique', intensity: 5, transitionType: 'crossfade', crossfadeDuration: 5 },
      { sceneId: 3, mood: 'Renaissance Beauty', intensity: 7, transitionType: 'crossfade', crossfadeDuration: 5 },
      { sceneId: 4, mood: 'French Impressionism', intensity: 6, transitionType: 'crossfade', crossfadeDuration: 5 },
      { sceneId: 5, mood: 'Modern Jazz', intensity: 8, transitionType: 'hard-cut' },
      { sceneId: 6, mood: 'Avant-garde', intensity: 9, transitionType: 'crossfade', crossfadeDuration: 4 },
      { sceneId: 7, mood: 'Electronic Future', intensity: 8, transitionType: 'fade' },
    ],
  },
  retentionHooks: {
    progressBar: {
      enabled: true,
      position: 'bottom',
      style: 'time-remaining',
    },
    factCardFrequency: 25,
    chapterTitles: true,
    transitionAnimations: true,
  },
});

/**
 * 6. Life Cycle Story Template
 * Example: Life and Death of a Star
 */
export const createLifeCycleStoryTemplate = (): LongFormStructure => ({
  genre: LongFormGenre.LIFE_CYCLE_STORY,
  totalDuration: 8,
  title: 'Life and Death of a Star',
  description: 'From birth to collapse: A billion-year journey',
  scenes: [
    {
      id: 1,
      title: 'Molecular Cloud: The Beginning',
      duration: 70,
      pieceCount: 500,
      imagePrompt: 'Molecular cloud nebula, stellar nursery, gas and dust collapsing, birth of stars, cosmic beauty',
      storyBeat: 'In the heart of vast clouds of gas and dust, stars are born',
      musicMood: 'Cosmic Genesis',
      factCards: [
        {
          timestamp: 15,
          type: 'statistic',
          content: '☁️ Cloud temperature: -260 degrees Celsius',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 50,
          type: 'fact',
          content: '⚛️ Gravity causes the cloud to collapse',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'fade',
    },
    {
      id: 2,
      title: 'Protostar: Stellar Infant',
      duration: 80,
      pieceCount: 600,
      imagePrompt: 'Protostar forming, accretion disk, stellar evolution, glowing core, nascent star',
      storyBeat: 'Pressure and heat increase, a young star takes shape',
      musicMood: 'Building Energy',
      factCards: [
        {
          timestamp: 20,
          type: 'fact',
          content: '🌡️ Core temperature: Several million degrees',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 60,
          type: 'statistic',
          content: '⏱️ Protostar phase: 100,000 years',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'zoom',
    },
    {
      id: 3,
      title: 'Main Sequence: Youth',
      duration: 90,
      pieceCount: 700,
      imagePrompt: 'Main sequence star, hydrogen fusion, stable energy output, our sun analog, radiant beauty',
      storyBeat: 'Nuclear reaction begins: Hydrogen converts to helium',
      musicMood: 'Stable Glory',
      factCards: [
        {
          timestamp: 25,
          type: 'statistic',
          content: '☀️ Our Sun is in this phase (4.6 billion years old)',
          duration: 5,
          position: 'center',
          animation: 'pop',
        },
        {
          timestamp: 70,
          type: 'fact',
          content: '⚡ 600 million tons of hydrogen burn every second',
          duration: 5,
          position: 'top',
          animation: 'slide',
        },
      ],
      transitionType: 'fade',
    },
    {
      id: 4,
      title: 'Red Giant: Old Age',
      duration: 90,
      pieceCount: 800,
      imagePrompt: 'Red giant star expanding, engulfing planets, helium fusion, dying star, dramatic transformation',
      storyBeat: 'Hydrogen runs out, the star expands',
      musicMood: 'Melancholic Expansion',
      factCards: [
        {
          timestamp: 20,
          type: 'fact',
          content: '🔴 The star\'s diameter grows 100 times',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 60,
          type: 'statistic',
          content: '🌍 In 5 billion years, the Sun will engulf Earth',
          duration: 5,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'zoom',
    },
    {
      id: 5,
      title: 'Planetary Nebula: Last Breath',
      duration: 80,
      pieceCount: 600,
      imagePrompt: 'Planetary nebula, expelled outer layers, glowing gases, beautiful death, cosmic artwork',
      storyBeat: 'The star\'s outer layers are ejected',
      musicMood: 'Ethereal Beauty',
      factCards: [
        {
          timestamp: 15,
          type: 'fact',
          content: '💨 Gas speed: 100,000 km per hour',
          duration: 5,
          position: 'top',
          animation: 'slide',
        },
        {
          timestamp: 60,
          type: 'quote',
          content: '"The most beautiful death in the cosmos"',
          duration: 4,
          position: 'center',
          animation: 'fade',
        },
      ],
      transitionType: 'fade',
    },
    {
      id: 6,
      title: 'White Dwarf: Ashes',
      duration: 70,
      pieceCount: 500,
      imagePrompt: 'White dwarf star, dense remnant core, cooling ember, end stage, cosmic graveyard',
      storyBeat: 'The compressed core remains: Incredible density',
      musicMood: 'Final Silence',
      factCards: [
        {
          timestamp: 15,
          type: 'statistic',
          content: '💎 Density: 1 teaspoon = 5 tons',
          duration: 5,
          position: 'top',
          animation: 'pop',
        },
        {
          timestamp: 50,
          type: 'fact',
          content: '❄️ Cools over trillions of years',
          duration: 4,
          position: 'bottom',
          animation: 'fade',
        },
      ],
      transitionType: 'fade',
    },
  ],
  musicStrategy: {
    type: 'dynamic-multi-track',
    tracks: [
      { sceneId: 1, mood: 'Cosmic Genesis', intensity: 4, transitionType: 'fade' },
      { sceneId: 2, mood: 'Building Energy', intensity: 6, transitionType: 'crossfade', crossfadeDuration: 5 },
      { sceneId: 3, mood: 'Stable Glory', intensity: 7, transitionType: 'crossfade', crossfadeDuration: 5 },
      { sceneId: 4, mood: 'Melancholic Expansion', intensity: 5, transitionType: 'crossfade', crossfadeDuration: 6 },
      { sceneId: 5, mood: 'Ethereal Beauty', intensity: 6, transitionType: 'crossfade', crossfadeDuration: 5 },
      { sceneId: 6, mood: 'Final Silence', intensity: 3, transitionType: 'fade' },
    ],
  },
  retentionHooks: {
    progressBar: {
      enabled: true,
      position: 'top',
      style: 'chapter-count',
    },
    factCardFrequency: 30,
    chapterTitles: true,
    transitionAnimations: true,
  },
});

/**
 * 7. Construction Timelapse Template
 * Example: Building the Eiffel Tower
 */
export const createConstructionTimelapseTemplate = (): LongFormStructure => ({
  genre: LongFormGenre.CONSTRUCTION_TIMELAPSE,
  totalDuration: 8,
  title: 'Building the Eiffel Tower: From Blueprint to Icon',
  description: 'The story of building one of the world\'s most famous structures',
  scenes: [
    {
      id: 1,
      title: 'Design: Gustave\'s Dream',
      duration: 70,
      pieceCount: 400,
      imagePrompt: 'Gustave Eiffel with tower blueprints, 19th century Paris, technical drawings, engineering genius',
      storyBeat: '1884: Gustave Eiffel presents a design for a 300-meter tower',
      musicMood: 'Industrial Dream',
      factCards: [
        {
          timestamp: 15,
          type: 'fact',
          content: '📐 Planned height: 300 meters',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 50,
          type: 'statistic',
          content: '💰 Budget: 6.5 million gold francs',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'fade',
    },
    {
      id: 2,
      title: 'Opposition: Battle of the Artists',
      duration: 60,
      pieceCount: 350,
      imagePrompt: 'Parisian artists protesting Eiffel Tower, 1887 Paris, controversy, newspapers, public outcry',
      storyBeat: '300 artists protested against the tower',
      musicMood: 'Controversy',
      factCards: [
        {
          timestamp: 15,
          type: 'quote',
          content: '"An ugly tower that will ruin Paris" - Artists',
          duration: 5,
          position: 'center',
          animation: 'pop',
        },
        {
          timestamp: 45,
          type: 'fact',
          content: '📰 Protest letter published in newspapers',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'hard-cut',
    },
    {
      id: 3,
      title: 'Foundations: Massive Base',
      duration: 90,
      pieceCount: 700,
      imagePrompt: 'Eiffel Tower foundation construction, workers, scaffolding, concrete base, 1887, industrial revolution',
      storyBeat: 'January 1887: Foundation construction began',
      musicMood: 'Heavy Industry',
      factCards: [
        {
          timestamp: 20,
          type: 'statistic',
          content: '🏗️ Foundation depth: 15 meters underground',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 65,
          type: 'fact',
          content: '👷 300 workers worked simultaneously',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'zoom',
    },
    {
      id: 4,
      title: 'Iron Framework: Rising to the Sky',
      duration: 100,
      pieceCount: 900,
      imagePrompt: 'Eiffel Tower mid-construction iron framework, workers on beams, 1888, dangerous heights, industrial marvel',
      storyBeat: '18,000 metal pieces form the structure',
      musicMood: 'Building Upward',
      factCards: [
        {
          timestamp: 25,
          type: 'statistic',
          content: '🔩 2.5 million rivets connect the pieces',
          duration: 5,
          position: 'top',
          animation: 'slide',
        },
        {
          timestamp: 75,
          type: 'fact',
          content: '⚠️ Only 1 worker died (safety record)',
          duration: 5,
          position: 'bottom',
          animation: 'fade',
        },
      ],
      transitionType: 'puzzle-wipe',
    },
    {
      id: 5,
      title: 'Completion: Symbol of Paris',
      duration: 80,
      pieceCount: 600,
      imagePrompt: 'Completed Eiffel Tower 1889, World Fair Paris, French flag on top, celebration, iconic landmark',
      storyBeat: 'March 1889: Tower completed - 2 years and 2 months of work',
      musicMood: 'Triumphant Victory',
      factCards: [
        {
          timestamp: 20,
          type: 'statistic',
          content: '🎉 Opened for the 1889 World\'s Fair',
          duration: 4,
          position: 'top',
          animation: 'pop',
        },
        {
          timestamp: 60,
          type: 'fact',
          content: '👑 Tallest building in the world until 1930',
          duration: 5,
          position: 'center',
          animation: 'fade',
        },
      ],
      transitionType: 'fade',
    },
    {
      id: 6,
      title: 'Legacy: 134 Years Later',
      duration: 70,
      pieceCount: 500,
      imagePrompt: 'Modern Eiffel Tower at night, illuminated, tourists, Paris skyline, timeless icon, celebration',
      storyBeat: 'Today: The world\'s most beloved landmark with 7 million annual visitors',
      musicMood: 'Eternal Glory',
      factCards: [
        {
          timestamp: 15,
          type: 'statistic',
          content: '🎫 300 million visitors in 134 years',
          duration: 5,
          position: 'top',
          animation: 'slide',
        },
        {
          timestamp: 50,
          type: 'quote',
          content: '"Paris without the Eiffel Tower is not Paris"',
          duration: 4,
          position: 'center',
          animation: 'fade',
        },
      ],
      transitionType: 'fade',
    },
  ],
  musicStrategy: {
    type: 'dynamic-multi-track',
    tracks: [
      { sceneId: 1, mood: 'Industrial Dream', intensity: 5, transitionType: 'fade' },
      { sceneId: 2, mood: 'Controversy', intensity: 6, transitionType: 'hard-cut' },
      { sceneId: 3, mood: 'Heavy Industry', intensity: 7, transitionType: 'crossfade', crossfadeDuration: 4 },
      { sceneId: 4, mood: 'Building Upward', intensity: 8, transitionType: 'crossfade', crossfadeDuration: 4 },
      { sceneId: 5, mood: 'Triumphant Victory', intensity: 9, transitionType: 'crossfade', crossfadeDuration: 5 },
      { sceneId: 6, mood: 'Eternal Glory', intensity: 7, transitionType: 'fade' },
    ],
  },
  retentionHooks: {
    progressBar: {
      enabled: true,
      position: 'bottom',
      style: 'time-remaining',
    },
    factCardFrequency: 25,
    chapterTitles: true,
    transitionAnimations: true,
  },
});

/**
 * 8. Story Arc Template
 * Example: The Legend of King Arthur
 */
export const createStoryArcTemplate = (): LongFormStructure => ({
  genre: LongFormGenre.STORY_ARC,
  totalDuration: 8,
  title: 'The Legend of King Arthur: Sword and Sorcery',
  description: 'The legendary tale of Britain\'s king, the sword Excalibur, and the Knights of the Round Table',
  scenes: [
    {
      id: 1,
      title: 'The Nameless Boy',
      duration: 70,
      pieceCount: 400,
      imagePrompt: 'Young Arthur pulling sword from stone, medieval England, Excalibur legend, destiny moment, cinematic',
      storyBeat: 'An orphan boy pulls a sword from a stone',
      musicMood: 'Mysterious Origins',
      factCards: [
        {
          timestamp: 15,
          type: 'quote',
          content: '"Whoso pulleth out this sword is rightwise king"',
          duration: 5,
          position: 'center',
          animation: 'fade',
        },
        {
          timestamp: 50,
          type: 'fact',
          content: '⚔️ Excalibur: A magical sword with legendary power',
          duration: 4,
          position: 'top',
          animation: 'slide',
        },
      ],
      transitionType: 'fade',
    },
    {
      id: 2,
      title: 'The Young King',
      duration: 80,
      pieceCount: 600,
      imagePrompt: 'King Arthur crowned, Camelot castle, knights gathering, medieval coronation, majestic kingdom',
      storyBeat: 'Arthur becomes king and builds Camelot',
      musicMood: 'Royal Triumph',
      factCards: [
        {
          timestamp: 20,
          type: 'fact',
          content: '🏰 Camelot: The legendary capital of Arthur\'s kingdom',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 60,
          type: 'statistic',
          content: '⚔️ Merlin the Wizard: Arthur\'s advisor and protector',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'zoom',
    },
    {
      id: 3,
      title: 'The Round Table',
      duration: 90,
      pieceCount: 700,
      imagePrompt: 'Knights of the Round Table, medieval great hall, chivalry oath, brotherhood, legendary warriors',
      storyBeat: 'Knights of the Round Table: A brotherhood of equals',
      musicMood: 'Brotherhood Epic',
      factCards: [
        {
          timestamp: 25,
          type: 'fact',
          content: '🛡️ Lancelot: The bravest knight',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 70,
          type: 'quote',
          content: '"At the Round Table, all are equal"',
          duration: 4,
          position: 'center',
          animation: 'pop',
        },
      ],
      transitionType: 'fade',
    },
    {
      id: 4,
      title: 'Quest for the Holy Grail',
      duration: 90,
      pieceCount: 800,
      imagePrompt: 'Quest for Holy Grail, knights on adventure, mystical forest, medieval quest, divine light',
      storyBeat: 'The search for the Holy Grail: A divine mission',
      musicMood: 'Mystical Quest',
      factCards: [
        {
          timestamp: 20,
          type: 'fact',
          content: '🏆 The Holy Grail: A cup with healing power',
          duration: 5,
          position: 'top',
          animation: 'slide',
        },
        {
          timestamp: 65,
          type: 'question',
          content: '❓ Which knight will find the Grail?',
          duration: 4,
          position: 'center',
          animation: 'pop',
        },
      ],
      transitionType: 'puzzle-wipe',
    },
    {
      id: 5,
      title: 'Betrayal',
      duration: 80,
      pieceCount: 600,
      imagePrompt: 'Betrayal at Camelot, Lancelot and Guinevere tragic romance, kingdom falling apart, dark atmosphere',
      storyBeat: 'Lancelot and Guinevere: A love that destroyed a kingdom',
      musicMood: 'Tragic Betrayal',
      factCards: [
        {
          timestamp: 15,
          type: 'fact',
          content: '💔 Guinevere: A queen torn between two loves',
          duration: 5,
          position: 'center',
          animation: 'fade',
        },
        {
          timestamp: 60,
          type: 'quote',
          content: '"Even the greatest kingdoms fall from within"',
          duration: 5,
          position: 'top',
          animation: 'slide',
        },
      ],
      transitionType: 'hard-cut',
    },
    {
      id: 6,
      title: 'The Final Battle',
      duration: 90,
      pieceCount: 900,
      imagePrompt: 'Battle of Camlann, Arthur vs Mordred, epic medieval battlefield, tragic final battle, dramatic sky',
      storyBeat: 'Battle of Camlann: Father against son',
      musicMood: 'Epic Battle',
      factCards: [
        {
          timestamp: 20,
          type: 'fact',
          content: '⚔️ Mordred: Arthur\'s treacherous son',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 70,
          type: 'statistic',
          content: '💀 Both perish in battle',
          duration: 5,
          position: 'center',
          animation: 'pop',
        },
      ],
      transitionType: 'fade',
    },
    {
      id: 7,
      title: 'Eternal Legend',
      duration: 70,
      pieceCount: 500,
      imagePrompt: 'Lady of the Lake retrieving Excalibur, mystical Avalon, Arthur immortal legend, magical farewell',
      storyBeat: 'Arthur goes to Avalon, but the legend lives on',
      musicMood: 'Eternal Legend',
      factCards: [
        {
          timestamp: 15,
          type: 'quote',
          content: '"The Once and Future King"',
          duration: 5,
          position: 'center',
          animation: 'fade',
        },
        {
          timestamp: 50,
          type: 'fact',
          content: '🗡️ Excalibur was returned to the lake',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'fade',
    },
  ],
  musicStrategy: {
    type: 'dynamic-multi-track',
    tracks: [
      { sceneId: 1, mood: 'Mysterious Origins', intensity: 5, transitionType: 'fade' },
      { sceneId: 2, mood: 'Royal Triumph', intensity: 7, transitionType: 'crossfade', crossfadeDuration: 5 },
      { sceneId: 3, mood: 'Brotherhood Epic', intensity: 8, transitionType: 'crossfade', crossfadeDuration: 4 },
      { sceneId: 4, mood: 'Mystical Quest', intensity: 6, transitionType: 'crossfade', crossfadeDuration: 5 },
      { sceneId: 5, mood: 'Tragic Betrayal', intensity: 5, transitionType: 'hard-cut' },
      { sceneId: 6, mood: 'Epic Battle', intensity: 10, transitionType: 'crossfade', crossfadeDuration: 4 },
      { sceneId: 7, mood: 'Eternal Legend', intensity: 6, transitionType: 'fade' },
    ],
  },
  retentionHooks: {
    progressBar: {
      enabled: true,
      position: 'bottom',
      style: 'chapter-count',
    },
    factCardFrequency: 30,
    chapterTitles: true,
    transitionAnimations: true,
  },
});

// Export all templates as a map for easy access
export const LONGFORM_TEMPLATES = {
  [LongFormGenre.HISTORICAL_RECONSTRUCTION]: createHistoricalReconstructionTemplate,
  [LongFormGenre.SCIENTIFIC_DEEPDIVE]: createScientificDeepdiveTemplate,
  [LongFormGenre.MYSTERY_REVEAL]: createMysteryRevealTemplate,
  [LongFormGenre.GEOGRAPHIC_JOURNEY]: createGeographicJourneyTemplate,
  [LongFormGenre.ART_EVOLUTION]: createArtEvolutionTemplate,
  [LongFormGenre.LIFE_CYCLE_STORY]: createLifeCycleStoryTemplate,
  [LongFormGenre.CONSTRUCTION_TIMELAPSE]: createConstructionTimelapseTemplate,
  [LongFormGenre.STORY_ARC]: createStoryArcTemplate,
};
