/**
 * Long-Form Genre Templates
 *
 * Ready-to-use templates for each of the 8 genres
 */

import {
  LongFormGenre,
  LongFormStructure,
  LongFormScene,
  FactCard,
} from '../../types-longform';

/**
 * 1. Historical Reconstruction Template
 * مثال: سقوط امپراتوری روم
 */
export const createHistoricalReconstructionTemplate = (): LongFormStructure => ({
  genre: LongFormGenre.HISTORICAL_RECONSTRUCTION,
  totalDuration: 8,
  title: 'سقوط امپراتوری روم: بازسازی تاریخی',
  description: 'سفری در زمان به دوران طلایی و سقوط یکی از بزرگترین امپراتوری‌های تاریخ',
  scenes: [
    {
      id: 1,
      title: 'دوران طلایی',
      duration: 80,
      pieceCount: 400,
      imagePrompt: 'Ancient Roman forum at golden hour, marble columns, bustling marketplace, citizens in togas, hyperrealistic',
      storyBeat: 'در سال ۱۱۷ میلادی، امپراتوری روم به وسیع‌ترین حد خود رسید',
      musicMood: 'Epic Glory',
      factCards: [
        {
          timestamp: 15,
          type: 'statistic',
          content: '🏛️ رم بر ۵ میلیون کیلومتر مربع حکم می‌راند',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 50,
          type: 'fact',
          content: '⚔️ ارتش روم ۳۰ لژیون داشت (۱۵۰٫۰۰۰ سرباز)',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'fade',
    },
    {
      id: 2,
      title: 'نخستین نشانه‌ها',
      duration: 90,
      pieceCount: 600,
      imagePrompt: 'Roman military camp under stormy sky, barbarian tribes in distance, tension, dramatic lighting',
      storyBeat: 'اما از سال ۲۳۵ میلادی، بحران شروع شد',
      musicMood: 'Building Tension',
      factCards: [
        {
          timestamp: 20,
          type: 'question',
          content: '❓ چه چیزی باعث سقوط روم شد؟',
          duration: 3,
          position: 'center',
          animation: 'pop',
        },
        {
          timestamp: 60,
          type: 'fact',
          content: '📉 در ۵۰ سال، ۲۶ امپراتور به قدرت رسیدند',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
      ],
      transitionType: 'puzzle-wipe',
    },
    {
      id: 3,
      title: 'حمله بربرها',
      duration: 100,
      pieceCount: 800,
      imagePrompt: 'Barbarian invasion, Rome under siege, burning buildings, chaos, epic battle scene',
      storyBeat: 'قبایل ژرمن و گوت‌ها به مرزهای امپراتوری حمله کردند',
      musicMood: 'Intense Battle',
      factCards: [
        {
          timestamp: 15,
          type: 'fact',
          content: '⚔️ نبرد آدریانوپل (۳۷۸ م): شکست بزرگ روم',
          duration: 4,
          position: 'top',
          animation: 'slide',
        },
        {
          timestamp: 50,
          type: 'countdown',
          content: '⏳ ۹۶ سال تا سقوط نهایی',
          duration: 3,
          position: 'bottom',
          animation: 'fade',
        },
        {
          timestamp: 80,
          type: 'quote',
          content: '"روم توسط بربرها نابود نشد، از درون پوسید" - تاریخ‌نگار',
          duration: 5,
          position: 'center',
          animation: 'fade',
        },
      ],
      transitionType: 'hard-cut',
    },
    {
      id: 4,
      title: 'تقسیم امپراتوری',
      duration: 70,
      pieceCount: 500,
      imagePrompt: 'Split Roman Empire map, Eastern and Western divisions, political intrigue, dramatic contrast',
      storyBeat: 'در سال ۳۹۵ میلادی، امپراتوری به دو بخش شرقی و غربی تقسیم شد',
      musicMood: 'Melancholic',
      factCards: [
        {
          timestamp: 15,
          type: 'fact',
          content: '🗺️ رم غربی: ضعیف | رم شرقی (بیزانس): قوی',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 50,
          type: 'statistic',
          content: '📊 رم غربی فقط ۸۱ سال دیگر دوام آورد',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'zoom',
    },
    {
      id: 5,
      title: 'سقوط نهایی',
      duration: 80,
      pieceCount: 600,
      imagePrompt: 'Fall of Rome 476 AD, barbarian king Odoacer deposing last emperor, ruins, sunset over fallen empire',
      storyBeat: 'در سال ۴۷۶ میلادی، آخرین امپراتور رم غربی برکنار شد',
      musicMood: 'Tragic Fall',
      factCards: [
        {
          timestamp: 15,
          type: 'fact',
          content: '👑 رومولوس آگوستولوس: آخرین امپراتور (۱۶ ساله)',
          duration: 5,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 50,
          type: 'statistic',
          content: '📅 ۱۲۲۹ سال از تاسیس رم گذشته بود',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'fade',
    },
    {
      id: 6,
      title: 'میراث جاودان',
      duration: 60,
      pieceCount: 400,
      imagePrompt: 'Modern Rome, Colosseum, ancient ruins merged with modern city, legacy of Rome, cinematic',
      storyBeat: 'اما میراث روم هرگز نمرد: حقوق، زبان، معماری، و تمدن',
      musicMood: 'Hopeful Legacy',
      factCards: [
        {
          timestamp: 15,
          type: 'fact',
          content: '🏛️ میراث روم: دموکراسی، حقوق، زبان، معماری',
          duration: 5,
          position: 'center',
          animation: 'pop',
        },
        {
          timestamp: 40,
          type: 'quote',
          content: '"تمام راه‌ها به رم ختم می‌شوند"',
          duration: 3,
          position: 'bottom',
          animation: 'fade',
        },
      ],
      transitionType: 'fade',
    },
  ],
  musicStrategy: {
    type: 'dynamic-multi-track',
    tracks: [
      { sceneId: 1, mood: 'Epic Glory', intensity: 7, transitionType: 'fade' },
      { sceneId: 2, mood: 'Building Tension', intensity: 5, transitionType: 'crossfade', crossfadeDuration: 4 },
      { sceneId: 3, mood: 'Intense Battle', intensity: 9, transitionType: 'hard-cut' },
      { sceneId: 4, mood: 'Melancholic', intensity: 4, transitionType: 'crossfade', crossfadeDuration: 5 },
      { sceneId: 5, mood: 'Tragic Fall', intensity: 8, transitionType: 'crossfade', crossfadeDuration: 4 },
      { sceneId: 6, mood: 'Hopeful Legacy', intensity: 6, transitionType: 'fade' },
    ],
  },
  retentionHooks: {
    progressBar: {
      enabled: true,
      position: 'bottom',
      style: 'chapter-count',
    },
    factCardFrequency: 25,
    chapterTitles: true,
    transitionAnimations: true,
  },
});

/**
 * 2. Scientific Deep-Dive Template
 * مثال: از کهکشان تا DNA
 */
export const createScientificDeepdiveTemplate = (): LongFormStructure => ({
  genre: LongFormGenre.SCIENTIFIC_DEEPDIVE,
  totalDuration: 8,
  title: 'از کهکشان تا DNA: سفر به اعماق هستی',
  description: 'یک سفر علمی شگفت‌انگیز از بزرگ‌ترین ساختار تا کوچک‌ترین واحد حیات',
  scenes: [
    {
      id: 1,
      title: 'کهکشان راه شیری',
      duration: 90,
      pieceCount: 500,
      imagePrompt: 'Milky Way galaxy from space, billions of stars, cosmic beauty, ultra detailed, scientific visualization',
      storyBeat: 'کهکشان ما حاوی ۲۰۰-۴۰۰ میلیارد ستاره است',
      musicMood: 'Cosmic Wonder',
      factCards: [
        {
          timestamp: 20,
          type: 'statistic',
          content: '🌌 قطر کهکشان: ۱۰۰٫۰۰۰ سال نوری',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 60,
          type: 'fact',
          content: '⭐ خورشید فقط یکی از میلیاردها ستاره است',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'zoom',
    },
    {
      id: 2,
      title: 'منظومه شمسی',
      duration: 90,
      pieceCount: 600,
      imagePrompt: 'Solar system with all planets, asteroid belt, detailed planetary textures, scientific accuracy',
      storyBeat: 'منظومه شمسی ما: ۸ سیاره، ۵ سیاره کوتوله، و میلیاردها سیارک',
      musicMood: 'Exploration',
      factCards: [
        {
          timestamp: 15,
          type: 'question',
          content: '❓ چرا پلوتو دیگر سیاره نیست؟',
          duration: 3,
          position: 'center',
          animation: 'pop',
        },
        {
          timestamp: 60,
          type: 'fact',
          content: '🪐 مشتری می‌تواند ۱۳۰۰ زمین را در خود جای دهد',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
      ],
      transitionType: 'zoom',
    },
    {
      id: 3,
      title: 'سیاره زمین',
      duration: 100,
      pieceCount: 800,
      imagePrompt: 'Earth from space, blue marble, clouds, continents, oceans, breathtaking view, NASA quality',
      storyBeat: 'تنها جهانی که حیات را در آن می‌شناسیم',
      musicMood: 'Earth Beauty',
      factCards: [
        {
          timestamp: 20,
          type: 'statistic',
          content: '🌍 سن زمین: ۴.۵ میلیارد سال',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 60,
          type: 'fact',
          content: '💧 ۷۱٪ سطح زمین اقیانوس است',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'zoom',
    },
    {
      id: 4,
      title: 'بدن انسان',
      duration: 80,
      pieceCount: 700,
      imagePrompt: 'Human anatomy, organs, circulatory system, scientific illustration, detailed, educational',
      storyBeat: 'بدن انسان: ماشینی پیچیده از ۳۷ تریلیون سلول',
      musicMood: 'Biological Wonder',
      factCards: [
        {
          timestamp: 15,
          type: 'statistic',
          content: '🫀 قلب در طول عمر ۲.۵ میلیارد بار می‌زند',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 55,
          type: 'fact',
          content: '🧠 مغز انسان ۸۶ میلیارد نورون دارد',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'zoom',
    },
    {
      id: 5,
      title: 'سلول',
      duration: 90,
      pieceCount: 900,
      imagePrompt: 'Human cell cross-section, nucleus, mitochondria, organelles, scientific accuracy, microscopic view',
      storyBeat: 'سلول: واحد بنیادی حیات',
      musicMood: 'Microscopic Discovery',
      factCards: [
        {
          timestamp: 20,
          type: 'fact',
          content: '🔬 میتوکندری: نیروگاه سلول',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 60,
          type: 'question',
          content: '❓ هسته سلول چه می‌کند؟',
          duration: 3,
          position: 'center',
          animation: 'pop',
        },
      ],
      transitionType: 'zoom',
    },
    {
      id: 6,
      title: 'DNA: نقشه حیات',
      duration: 70,
      pieceCount: 600,
      imagePrompt: 'DNA double helix, genetic code, colorful base pairs, scientific beauty, ultra detailed',
      storyBeat: 'DNA: کتابی که داستان تمام موجودات زنده را روایت می‌کند',
      musicMood: 'Genetic Code',
      factCards: [
        {
          timestamp: 15,
          type: 'statistic',
          content: '🧬 DNA انسان ۳ میلیارد جفت باز دارد',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 45,
          type: 'fact',
          content: '🔗 اگر DNA سلولی را باز کنید، ۲ متر طول دارد!',
          duration: 5,
          position: 'center',
          animation: 'pop',
        },
      ],
      transitionType: 'fade',
    },
  ],
  musicStrategy: {
    type: 'single-track',
    tracks: [
      { sceneId: 1, mood: 'Cosmic Documentary', intensity: 6, transitionType: 'fade' },
    ],
  },
  retentionHooks: {
    progressBar: {
      enabled: true,
      position: 'top',
      style: 'percentage',
    },
    factCardFrequency: 20,
    chapterTitles: true,
    transitionAnimations: true,
  },
});

/**
 * 3. Mystery Reveal Template
 * مثال: معمای مثلث برمودا
 */
export const createMysteryRevealTemplate = (): LongFormStructure => ({
  genre: LongFormGenre.MYSTERY_REVEAL,
  totalDuration: 8,
  title: 'مثلث برمودا: حقیقت پشت معما',
  description: 'آیا واقعاً کشتی‌ها و هواپیماها در مثلث برمودا ناپدید می‌شوند؟',
  scenes: [
    {
      id: 1,
      title: 'رویداد مرموز',
      duration: 70,
      pieceCount: 400,
      imagePrompt: 'Bermuda Triangle from above, stormy ocean, mysterious fog, disappearing plane, cinematic',
      storyBeat: 'دسامبر ۱۹۴۵: پنج هواپیمای نیروی دریایی آمریکا ناپدید شدند',
      musicMood: 'Suspenseful Mystery',
      factCards: [
        {
          timestamp: 15,
          type: 'fact',
          content: '✈️ پرواز ۱۹: ۵ هواپیما، ۱۴ خلبان، همگی ناپدید شدند',
          duration: 5,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 50,
          type: 'question',
          content: '❓ چه اتفاقی افتاد؟',
          duration: 3,
          position: 'center',
          animation: 'pop',
        },
      ],
      transitionType: 'fade',
    },
    {
      id: 2,
      title: 'نظریه ۱: امواج غول‌پیکر',
      duration: 90,
      pieceCount: 600,
      imagePrompt: 'Rogue wave, massive ocean wave towering over ship, dramatic, realistic, terrifying',
      storyBeat: 'آیا امواج غول‌پیکر مسئول هستند؟',
      musicMood: 'Tension',
      factCards: [
        {
          timestamp: 20,
          type: 'statistic',
          content: '🌊 ارتفاع موج: تا ۳۰ متر (ارتفاع ساختمان ۱۰ طبقه)',
          duration: 5,
          position: 'top',
          animation: 'slide',
        },
        {
          timestamp: 65,
          type: 'fact',
          content: '⚠️ امواج غول‌پیکر می‌توانند ناگهانی ظاهر شوند',
          duration: 4,
          position: 'bottom',
          animation: 'fade',
        },
      ],
      transitionType: 'puzzle-wipe',
    },
    {
      id: 3,
      title: 'نظریه ۲: میدان مغناطیسی',
      duration: 90,
      pieceCount: 700,
      imagePrompt: 'Magnetic anomaly, compass going haywire, electromagnetic interference, scientific visualization',
      storyBeat: 'آیا میدان مغناطیسی قطب‌نما را گمراه می‌کند؟',
      musicMood: 'Scientific Investigation',
      factCards: [
        {
          timestamp: 20,
          type: 'fact',
          content: '🧭 قطب‌نماها در این منطقه رفتار غیرعادی دارند',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 65,
          type: 'statistic',
          content: '📊 اما تحقیقات نشان می‌دهد این تأثیر ناچیز است',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'hard-cut',
    },
    {
      id: 4,
      title: 'نظریه ۳: متان از اعماق',
      duration: 80,
      pieceCount: 600,
      imagePrompt: 'Methane bubbles rising from ocean floor, underwater explosion, ship sinking, scientific accuracy',
      storyBeat: 'آیا گاز متان از بستر اقیانوس کشتی‌ها را غرق می‌کند؟',
      musicMood: 'Revelation',
      factCards: [
        {
          timestamp: 20,
          type: 'fact',
          content: '💨 حباب‌های متان می‌توانند چگالی آب را کاهش دهند',
          duration: 5,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 60,
          type: 'statistic',
          content: '🔬 آزمایش‌ها این نظریه را تأیید کردند',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'zoom',
    },
    {
      id: 5,
      title: 'حقیقت',
      duration: 90,
      pieceCount: 700,
      imagePrompt: 'Bermuda Triangle map with shipping lanes, busy ocean traffic, normal maritime activity',
      storyBeat: 'حقیقت: مثلث برمودا خطرناک‌تر از سایر مناطق نیست!',
      musicMood: 'Truth Revealed',
      factCards: [
        {
          timestamp: 20,
          type: 'statistic',
          content: '📊 نرخ حادثه در مثلث برمودا طبیعی است',
          duration: 5,
          position: 'center',
          animation: 'pop',
        },
        {
          timestamp: 60,
          type: 'fact',
          content: '✅ بیمه دریایی: بدون افزایش نرخ',
          duration: 4,
          position: 'bottom',
          animation: 'fade',
        },
      ],
      transitionType: 'fade',
    },
    {
      id: 6,
      title: 'پایان معما',
      duration: 60,
      pieceCount: 400,
      imagePrompt: 'Calm Bermuda Triangle, beautiful sunset, peaceful ocean, debunked myth, closure',
      storyBeat: 'افسانه مثلث برمودا: ترکیبی از اغراق رسانه‌ای و خطای انسانی',
      musicMood: 'Peaceful Conclusion',
      factCards: [
        {
          timestamp: 15,
          type: 'quote',
          content: '"حقیقت اغلب ساده‌تر از افسانه است"',
          duration: 4,
          position: 'center',
          animation: 'fade',
        },
        {
          timestamp: 45,
          type: 'fact',
          content: '🌍 هزاران کشتی و هواپیما هر روز ایمن عبور می‌کنند',
          duration: 5,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'fade',
    },
  ],
  musicStrategy: {
    type: 'single-track',
    tracks: [
      { sceneId: 1, mood: 'Mystery Documentary', intensity: 7, transitionType: 'fade' },
    ],
  },
  retentionHooks: {
    progressBar: {
      enabled: true,
      position: 'bottom',
      style: 'time-remaining',
    },
    factCardFrequency: 20,
    chapterTitles: true,
    transitionAnimations: true,
  },
});

/**
 * 4. Geographic Journey Template
 * مثال: عجایب هفتگانه جهان
 */
export const createGeographicJourneyTemplate = (): LongFormStructure => ({
  genre: LongFormGenre.GEOGRAPHIC_JOURNEY,
  totalDuration: 8,
  title: 'عجایب هفتگانه جدید: سفری در سرتاسر دنیا',
  description: 'بازدید مجازی از هفت شاهکار معماری و طبیعی جهان',
  scenes: [
    {
      id: 1,
      title: 'دیوار بزرگ چین',
      duration: 70,
      pieceCount: 500,
      imagePrompt: 'Great Wall of China winding through misty mountains, aerial view, sunrise, majestic, cinematic',
      storyBeat: 'بلندترین سازه بشری: ۲۱٬۰۰۰ کیلومتر طول',
      musicMood: 'Asian Epic',
      factCards: [
        {
          timestamp: 15,
          type: 'statistic',
          content: '🏯 ساخت: ۲۷۰۰ سال پیش تا ۴۰۰ سال پیش',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 50,
          type: 'fact',
          content: '👷 میلیون‌ها کارگر در ساخت آن شرکت کردند',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'fade',
    },
    {
      id: 2,
      title: 'مجسمه مسیح نجات‌دهنده',
      duration: 65,
      pieceCount: 400,
      imagePrompt: 'Christ the Redeemer statue Rio de Janeiro, sunset, dramatic clouds, iconic pose, breathtaking',
      storyBeat: 'ریو دوژانیرو، برزیل: نماد امید و آغوش باز',
      musicMood: 'Latin Spirit',
      factCards: [
        {
          timestamp: 15,
          type: 'statistic',
          content: '🗿 ارتفاع: ۳۰ متر | وزن: ۶۳۵ تن',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 45,
          type: 'fact',
          content: '⚡ رعد و برق سالانه چندین بار به آن اصابت می‌کند',
          duration: 5,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'zoom',
    },
    {
      id: 3,
      title: 'ماچو پیچو',
      duration: 85,
      pieceCount: 700,
      imagePrompt: 'Machu Picchu ancient Inca citadel in clouds, mountain peaks, mystical atmosphere, UNESCO heritage',
      storyBeat: 'شهر گمشده اینکاها در ارتفاع ۲٬۴۳۰ متری',
      musicMood: 'Andean Mystery',
      factCards: [
        {
          timestamp: 20,
          type: 'fact',
          content: '🏔️ ساخته شده در قرن ۱۵ میلادی',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 60,
          type: 'question',
          content: '❓ چگونه اینکاها سنگ‌های عظیم را جابجا کردند؟',
          duration: 4,
          position: 'center',
          animation: 'pop',
        },
      ],
      transitionType: 'puzzle-wipe',
    },
    {
      id: 4,
      title: 'کولوسئوم رم',
      duration: 80,
      pieceCount: 600,
      imagePrompt: 'Colosseum Rome at golden hour, ancient amphitheater, gladiator arena, historical marvel',
      storyBeat: 'آمفی‌تئاتر باشکوه روم: شاهد نبردهای گلادیاتورها',
      musicMood: 'Roman Glory',
      factCards: [
        {
          timestamp: 15,
          type: 'statistic',
          content: '🏛️ ظرفیت: ۵۰٬۰۰۰ تماشاگر',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 55,
          type: 'fact',
          content: '⚔️ نبردهای دریایی نیز در اینجا برگزار می‌شد',
          duration: 5,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'hard-cut',
    },
    {
      id: 5,
      title: 'تاج محل',
      duration: 80,
      pieceCount: 650,
      imagePrompt: 'Taj Mahal at dawn, white marble reflecting in pool, symmetrical beauty, Islamic architecture masterpiece',
      storyBeat: 'آرامگاه عشق: شاهکار معماری اسلامی هند',
      musicMood: 'Indian Serenity',
      factCards: [
        {
          timestamp: 20,
          type: 'quote',
          content: '"سنگ مرمری که عشق را روایت می‌کند"',
          duration: 4,
          position: 'center',
          animation: 'fade',
        },
        {
          timestamp: 60,
          type: 'statistic',
          content: '💎 ۲۲ سال ساخت | ۲۰٬۰۰۰ کارگر',
          duration: 4,
          position: 'top',
          animation: 'slide',
        },
      ],
      transitionType: 'fade',
    },
    {
      id: 6,
      title: 'چیچن ایتزا',
      duration: 70,
      pieceCount: 550,
      imagePrompt: 'Chichen Itza El Castillo pyramid Mexico, Maya calendar temple, archaeological wonder, dramatic sky',
      storyBeat: 'هرم کوکولکان: تقویم خورشیدی مایاها',
      musicMood: 'Maya Wonder',
      factCards: [
        {
          timestamp: 15,
          type: 'fact',
          content: '🔺 ۹۱ پله در هر طرف + یک پله بالا = ۳۶۵ روز',
          duration: 5,
          position: 'top',
          animation: 'pop',
        },
        {
          timestamp: 50,
          type: 'statistic',
          content: '🌅 در اعتدال بهاری، سایه مار ظاهر می‌شود',
          duration: 5,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'zoom',
    },
    {
      id: 7,
      title: 'پترا',
      duration: 70,
      pieceCount: 500,
      imagePrompt: 'Petra Jordan, Al-Khazneh treasury carved in red rock, ancient Nabataean city, rose-red city',
      storyBeat: 'شهر صخره‌ای: پایتخت نباتی‌ها در قلب صحرا',
      musicMood: 'Desert Majesty',
      factCards: [
        {
          timestamp: 15,
          type: 'fact',
          content: '🏜️ کشف مجدد در سال ۱۸۱۲ میلادی',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 50,
          type: 'quote',
          content: '"شهری گلرنگ، به قدمت نیمی از زمان" - شعر انگلیسی',
          duration: 5,
          position: 'center',
          animation: 'fade',
        },
      ],
      transitionType: 'fade',
    },
  ],
  musicStrategy: {
    type: 'dynamic-multi-track',
    tracks: [
      { sceneId: 1, mood: 'Asian Epic', intensity: 6, transitionType: 'crossfade', crossfadeDuration: 4 },
      { sceneId: 2, mood: 'Latin Spirit', intensity: 7, transitionType: 'crossfade', crossfadeDuration: 4 },
      { sceneId: 3, mood: 'Andean Mystery', intensity: 5, transitionType: 'crossfade', crossfadeDuration: 4 },
      { sceneId: 4, mood: 'Roman Glory', intensity: 8, transitionType: 'crossfade', crossfadeDuration: 4 },
      { sceneId: 5, mood: 'Indian Serenity', intensity: 5, transitionType: 'crossfade', crossfadeDuration: 5 },
      { sceneId: 6, mood: 'Maya Wonder', intensity: 6, transitionType: 'crossfade', crossfadeDuration: 4 },
      { sceneId: 7, mood: 'Desert Majesty', intensity: 7, transitionType: 'fade' },
    ],
  },
  retentionHooks: {
    progressBar: {
      enabled: true,
      position: 'top',
      style: 'chapter-count',
    },
    factCardFrequency: 30,
    chapterTitles: true,
    transitionAnimations: true,
  },
});

/**
 * 5. Art Evolution Template
 * مثال: تاریخ نقاشی از غارها تا دیجیتال
 */
export const createArtEvolutionTemplate = (): LongFormStructure => ({
  genre: LongFormGenre.ART_EVOLUTION,
  totalDuration: 8,
  title: 'تکامل هنر نقاشی: از غارهای باستان تا آرت دیجیتال',
  description: 'سفری ۴۰٬۰۰۰ ساله در تاریخ نقاشی بشر',
  scenes: [
    {
      id: 1,
      title: 'نقاشی‌های غار',
      duration: 70,
      pieceCount: 400,
      imagePrompt: 'Cave painting prehistoric art, bison and horses on rock wall, Lascaux style, ancient humanity',
      storyBeat: '۴۰٬۰۰۰ سال پیش: نخستین هنرمندان انسان',
      musicMood: 'Primal Drums',
      factCards: [
        {
          timestamp: 15,
          type: 'statistic',
          content: '🦬 غار لاسکو: ۱۷٬۰۰۰ سال قدمت',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 50,
          type: 'fact',
          content: '🎨 رنگدانه‌ها: اکسید آهن، ذغال، گچ',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'fade',
    },
    {
      id: 2,
      title: 'هنر مصر باستان',
      duration: 80,
      pieceCount: 600,
      imagePrompt: 'Ancient Egyptian art, hieroglyphics, profile figures, papyrus paintings, golden age, detailed',
      storyBeat: 'مصر باستان: هنر برای ابدیت',
      musicMood: 'Egyptian Mystique',
      factCards: [
        {
          timestamp: 20,
          type: 'fact',
          content: '👁️ قانون نمایش رو به جلو: چهره نیمرخ، چشم رو به رو',
          duration: 5,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 60,
          type: 'statistic',
          content: '📜 هنر مصری ۳٬۰۰۰ سال تقریباً بدون تغییر ماند',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'zoom',
    },
    {
      id: 3,
      title: 'رنسانس: انقلاب هنر',
      duration: 100,
      pieceCount: 800,
      imagePrompt: 'Renaissance masterpiece, Mona Lisa style, sfumato technique, Leonardo da Vinci quality, realistic portrait',
      storyBeat: 'قرن ۱۵-۱۶: بازگشت به واقع‌گرایی و انسان‌محوری',
      musicMood: 'Renaissance Beauty',
      factCards: [
        {
          timestamp: 25,
          type: 'quote',
          content: '"هنر علم قابل دیدن است" - لئوناردو داوینچی',
          duration: 5,
          position: 'center',
          animation: 'fade',
        },
        {
          timestamp: 70,
          type: 'fact',
          content: '🎨 نوآوری: پرسپکتیو، نورپردازی، آناتومی دقیق',
          duration: 5,
          position: 'top',
          animation: 'slide',
        },
      ],
      transitionType: 'puzzle-wipe',
    },
    {
      id: 4,
      title: 'امپرسیونیسم: لحظه را بگیر',
      duration: 90,
      pieceCount: 700,
      imagePrompt: 'Impressionist painting, water lilies, broken brushstrokes, light and color, Monet style, dreamy',
      storyBeat: 'قرن ۱۹: هنرمندان به خارج از استودیو رفتند',
      musicMood: 'French Impressionism',
      factCards: [
        {
          timestamp: 20,
          type: 'fact',
          content: '🌅 کلود مونه: ۲۵۰ نقاشی از نیلوفرهای آبی',
          duration: 5,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 65,
          type: 'statistic',
          content: '🎨 تکنیک: ضربه‌های قلم مو ظاهر، رنگ خالص',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'fade',
    },
    {
      id: 5,
      title: 'کوبیسم: واقعیت شکسته',
      duration: 80,
      pieceCount: 600,
      imagePrompt: 'Cubist painting, geometric shapes, multiple perspectives, Picasso style, abstract fragmented reality',
      storyBeat: 'قرن ۲۰: پیکاسو و براک واقعیت را شکستند',
      musicMood: 'Modern Jazz',
      factCards: [
        {
          timestamp: 15,
          type: 'question',
          content: '❓ چرا چندین دیدگاه را در یک نقاشی نشان دهیم؟',
          duration: 4,
          position: 'center',
          animation: 'pop',
        },
        {
          timestamp: 55,
          type: 'fact',
          content: '🎨 پیکاسو: "هنر دروغی است که حقیقت را نشان می‌دهد"',
          duration: 5,
          position: 'top',
          animation: 'fade',
        },
      ],
      transitionType: 'hard-cut',
    },
    {
      id: 6,
      title: 'هنر آبستره: آزادی مطلق',
      duration: 70,
      pieceCount: 500,
      imagePrompt: 'Abstract expressionism, Jackson Pollock drip painting, color explosion, emotional chaos, pure emotion',
      storyBeat: '۱۹۵۰: هنر بدون موضوع، فقط احساس',
      musicMood: 'Avant-garde',
      factCards: [
        {
          timestamp: 15,
          type: 'fact',
          content: '🎨 جکسون پولاک: تکنیک قطره‌چکانی',
          duration: 4,
          position: 'top',
          animation: 'slide',
        },
        {
          timestamp: 50,
          type: 'quote',
          content: '"وقتی در نقاشی هستم، از آنچه می‌کنم آگاه نیستم"',
          duration: 5,
          position: 'center',
          animation: 'fade',
        },
      ],
      transitionType: 'zoom',
    },
    {
      id: 7,
      title: 'آرت دیجیتال: مرز جدید',
      duration: 70,
      pieceCount: 900,
      imagePrompt: 'Digital art NFT, futuristic artwork, AI-generated art, glitch art, cyberpunk aesthetic, modern technology',
      storyBeat: 'قرن ۲۱: هنر در دنیای دیجیتال و NFT',
      musicMood: 'Electronic Future',
      factCards: [
        {
          timestamp: 15,
          type: 'statistic',
          content: '💰 اولین NFT: فروخته شده به قیمت ۶۹ میلیون دلار',
          duration: 5,
          position: 'top',
          animation: 'pop',
        },
        {
          timestamp: 50,
          type: 'fact',
          content: '🤖 هوش مصنوعی اکنون می‌تواند هنر خلق کند',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'fade',
    },
  ],
  musicStrategy: {
    type: 'dynamic-multi-track',
    tracks: [
      { sceneId: 1, mood: 'Primal Drums', intensity: 4, transitionType: 'fade' },
      { sceneId: 2, mood: 'Egyptian Mystique', intensity: 5, transitionType: 'crossfade', crossfadeDuration: 5 },
      { sceneId: 3, mood: 'Renaissance Beauty', intensity: 7, transitionType: 'crossfade', crossfadeDuration: 5 },
      { sceneId: 4, mood: 'French Impressionism', intensity: 6, transitionType: 'crossfade', crossfadeDuration: 5 },
      { sceneId: 5, mood: 'Modern Jazz', intensity: 8, transitionType: 'hard-cut' },
      { sceneId: 6, mood: 'Avant-garde', intensity: 9, transitionType: 'crossfade', crossfadeDuration: 4 },
      { sceneId: 7, mood: 'Electronic Future', intensity: 8, transitionType: 'fade' },
    ],
  },
  retentionHooks: {
    progressBar: {
      enabled: true,
      position: 'bottom',
      style: 'time-remaining',
    },
    factCardFrequency: 25,
    chapterTitles: true,
    transitionAnimations: true,
  },
});

/**
 * 6. Life Cycle Story Template
 * مثال: چرخه حیات یک ستاره
 */
export const createLifeCycleStoryTemplate = (): LongFormStructure => ({
  genre: LongFormGenre.LIFE_CYCLE_STORY,
  totalDuration: 8,
  title: 'زندگی و مرگ یک ستاره',
  description: 'از تولد تا فروپاشی: سفری میلیارد ساله',
  scenes: [
    {
      id: 1,
      title: 'ابر مولکولی: آغاز',
      duration: 70,
      pieceCount: 500,
      imagePrompt: 'Molecular cloud nebula, stellar nursery, gas and dust collapsing, birth of stars, cosmic beauty',
      storyBeat: 'در قلب ابرهای عظیم گاز و غبار، ستاره‌ها متولد می‌شوند',
      musicMood: 'Cosmic Genesis',
      factCards: [
        {
          timestamp: 15,
          type: 'statistic',
          content: '☁️ دمای ابر: منفی ۲۶۰ درجه سانتیگراد',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 50,
          type: 'fact',
          content: '⚛️ گرانش باعث فروپاشی ابر می‌شود',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'fade',
    },
    {
      id: 2,
      title: 'پروتوستاره: نوزاد ستاره‌ای',
      duration: 80,
      pieceCount: 600,
      imagePrompt: 'Protostar forming, accretion disk, stellar evolution, glowing core, nascent star',
      storyBeat: 'فشار و حرارت افزایش می‌یابد، یک ستاره نوپا شکل می‌گیرد',
      musicMood: 'Building Energy',
      factCards: [
        {
          timestamp: 20,
          type: 'fact',
          content: '🌡️ دمای هسته: چندین میلیون درجه',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 60,
          type: 'statistic',
          content: '⏱️ مرحله پروتوستاره: ۱۰۰٬۰۰۰ سال',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'zoom',
    },
    {
      id: 3,
      title: 'دنباله اصلی: جوانی',
      duration: 90,
      pieceCount: 700,
      imagePrompt: 'Main sequence star, hydrogen fusion, stable energy output, our sun analog, radiant beauty',
      storyBeat: 'واکنش هسته‌ای آغاز می‌شود: هیدروژن به هلیوم تبدیل می‌شود',
      musicMood: 'Stable Glory',
      factCards: [
        {
          timestamp: 25,
          type: 'statistic',
          content: '☀️ خورشید ما در این مرحله است (۴.۶ میلیارد سال)',
          duration: 5,
          position: 'center',
          animation: 'pop',
        },
        {
          timestamp: 70,
          type: 'fact',
          content: '⚡ در هر ثانیه ۶۰۰ میلیون تن هیدروژن می‌سوزد',
          duration: 5,
          position: 'top',
          animation: 'slide',
        },
      ],
      transitionType: 'fade',
    },
    {
      id: 4,
      title: 'غول سرخ: پیری',
      duration: 90,
      pieceCount: 800,
      imagePrompt: 'Red giant star expanding, engulfing planets, helium fusion, dying star, dramatic transformation',
      storyBeat: 'هیدروژن تمام می‌شود، ستاره منبسط می‌شود',
      musicMood: 'Melancholic Expansion',
      factCards: [
        {
          timestamp: 20,
          type: 'fact',
          content: '🔴 قطر ستاره ۱۰۰ برابر می‌شود',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 60,
          type: 'statistic',
          content: '🌍 خورشید در ۵ میلیارد سال زمین را خواهد بلعید',
          duration: 5,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'zoom',
    },
    {
      id: 5,
      title: 'سحابی سیاره‌ای: نفس آخر',
      duration: 80,
      pieceCount: 600,
      imagePrompt: 'Planetary nebula, expelled outer layers, glowing gases, beautiful death, cosmic artwork',
      storyBeat: 'لایه‌های بیرونی ستاره پرتاب می‌شوند',
      musicMood: 'Ethereal Beauty',
      factCards: [
        {
          timestamp: 15,
          type: 'fact',
          content: '💨 سرعت گازها: ۱۰۰٬۰۰۰ کیلومتر در ساعت',
          duration: 5,
          position: 'top',
          animation: 'slide',
        },
        {
          timestamp: 60,
          type: 'quote',
          content: '"زیباترین مرگ در کیهان"',
          duration: 4,
          position: 'center',
          animation: 'fade',
        },
      ],
      transitionType: 'fade',
    },
    {
      id: 6,
      title: 'کوتوله سفید: خاکستر',
      duration: 70,
      pieceCount: 500,
      imagePrompt: 'White dwarf star, dense remnant core, cooling ember, end stage, cosmic graveyard',
      storyBeat: 'هسته فشرده باقی می‌ماند: چگالی شگفت‌انگیز',
      musicMood: 'Final Silence',
      factCards: [
        {
          timestamp: 15,
          type: 'statistic',
          content: '💎 چگالی: ۱ قاشق چای‌خوری = ۵ تن',
          duration: 5,
          position: 'top',
          animation: 'pop',
        },
        {
          timestamp: 50,
          type: 'fact',
          content: '❄️ طی تریلیون‌ها سال سرد می‌شود',
          duration: 4,
          position: 'bottom',
          animation: 'fade',
        },
      ],
      transitionType: 'fade',
    },
  ],
  musicStrategy: {
    type: 'dynamic-multi-track',
    tracks: [
      { sceneId: 1, mood: 'Cosmic Genesis', intensity: 4, transitionType: 'fade' },
      { sceneId: 2, mood: 'Building Energy', intensity: 6, transitionType: 'crossfade', crossfadeDuration: 5 },
      { sceneId: 3, mood: 'Stable Glory', intensity: 7, transitionType: 'crossfade', crossfadeDuration: 5 },
      { sceneId: 4, mood: 'Melancholic Expansion', intensity: 5, transitionType: 'crossfade', crossfadeDuration: 6 },
      { sceneId: 5, mood: 'Ethereal Beauty', intensity: 6, transitionType: 'crossfade', crossfadeDuration: 5 },
      { sceneId: 6, mood: 'Final Silence', intensity: 3, transitionType: 'fade' },
    ],
  },
  retentionHooks: {
    progressBar: {
      enabled: true,
      position: 'top',
      style: 'chapter-count',
    },
    factCardFrequency: 30,
    chapterTitles: true,
    transitionAnimations: true,
  },
});

/**
 * 7. Construction Timelapse Template
 * مثال: ساخت برج ایفل
 */
export const createConstructionTimelapseTemplate = (): LongFormStructure => ({
  genre: LongFormGenre.CONSTRUCTION_TIMELAPSE,
  totalDuration: 8,
  title: 'ساخت برج ایفل: از نقشه تا نماد',
  description: 'روایت ساخت یکی از مشهورترین سازه‌های جهان',
  scenes: [
    {
      id: 1,
      title: 'طراحی: رویای گوستاو',
      duration: 70,
      pieceCount: 400,
      imagePrompt: 'Gustave Eiffel with tower blueprints, 19th century Paris, technical drawings, engineering genius',
      storyBeat: '۱۸۸۴: گوستاو ایفل طرح برجی ۳۰۰ متری ارائه می‌دهد',
      musicMood: 'Industrial Dream',
      factCards: [
        {
          timestamp: 15,
          type: 'fact',
          content: '📐 ارتفاع برنامه‌ریزی شده: ۳۰۰ متر',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 50,
          type: 'statistic',
          content: '💰 بودجه: ۶.۵ میلیون فرانک طلا',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'fade',
    },
    {
      id: 2,
      title: 'مخالفت‌ها: نبرد هنرمندان',
      duration: 60,
      pieceCount: 350,
      imagePrompt: 'Parisian artists protesting Eiffel Tower, 1887 Paris, controversy, newspapers, public outcry',
      storyBeat: '۳۰۰ هنرمند علیه برج اعتراض کردند',
      musicMood: 'Controversy',
      factCards: [
        {
          timestamp: 15,
          type: 'quote',
          content: '"برجی زشت که پاریس را خراب می‌کند" - هنرمندان',
          duration: 5,
          position: 'center',
          animation: 'pop',
        },
        {
          timestamp: 45,
          type: 'fact',
          content: '📰 نامه اعتراضی در روزنامه‌ها منتشر شد',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'hard-cut',
    },
    {
      id: 3,
      title: 'پایه‌ها: شالوده عظیم',
      duration: 90,
      pieceCount: 700,
      imagePrompt: 'Eiffel Tower foundation construction, workers, scaffolding, concrete base, 1887, industrial revolution',
      storyBeat: 'ژانویه ۱۸۸۷: ساخت پایه‌ها آغاز شد',
      musicMood: 'Heavy Industry',
      factCards: [
        {
          timestamp: 20,
          type: 'statistic',
          content: '🏗️ عمق پایه‌ها: ۱۵ متر زیر زمین',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 65,
          type: 'fact',
          content: '👷 ۳۰۰ کارگر همزمان کار می‌کردند',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'zoom',
    },
    {
      id: 4,
      title: 'ساختار فلزی: صعود به آسمان',
      duration: 100,
      pieceCount: 900,
      imagePrompt: 'Eiffel Tower mid-construction iron framework, workers on beams, 1888, dangerous heights, industrial marvel',
      storyBeat: '۱۸٬۰۰۰ قطعه فلزی سازه را شکل می‌دهند',
      musicMood: 'Building Upward',
      factCards: [
        {
          timestamp: 25,
          type: 'statistic',
          content: '🔩 ۲.۵ میلیون پرچ برای اتصال قطعات',
          duration: 5,
          position: 'top',
          animation: 'slide',
        },
        {
          timestamp: 75,
          type: 'fact',
          content: '⚠️ فقط ۱ کارگر جان خود را از دست داد (رکورد ایمنی)',
          duration: 5,
          position: 'bottom',
          animation: 'fade',
        },
      ],
      transitionType: 'puzzle-wipe',
    },
    {
      id: 5,
      title: 'تکمیل: نماد پاریس',
      duration: 80,
      pieceCount: 600,
      imagePrompt: 'Completed Eiffel Tower 1889, World Fair Paris, French flag on top, celebration, iconic landmark',
      storyBeat: 'مارس ۱۸۸۹: برج تکمیل شد - ۲ سال و ۲ ماه کار',
      musicMood: 'Triumphant Victory',
      factCards: [
        {
          timestamp: 20,
          type: 'statistic',
          content: '🎉 افتتاح در نمایشگاه جهانی ۱۸۸۹',
          duration: 4,
          position: 'top',
          animation: 'pop',
        },
        {
          timestamp: 60,
          type: 'fact',
          content: '👑 بلندترین ساختمان جهان تا سال ۱۹۳۰',
          duration: 5,
          position: 'center',
          animation: 'fade',
        },
      ],
      transitionType: 'fade',
    },
    {
      id: 6,
      title: 'میراث: ۱۳۴ سال بعد',
      duration: 70,
      pieceCount: 500,
      imagePrompt: 'Modern Eiffel Tower at night, illuminated, tourists, Paris skyline, timeless icon, celebration',
      storyBeat: 'امروز: محبوب‌ترین بنای جهان با ۷ میلیون بازدیدکننده سالانه',
      musicMood: 'Eternal Glory',
      factCards: [
        {
          timestamp: 15,
          type: 'statistic',
          content: '🎫 ۳۰۰ میلیون بازدیدکننده در ۱۳۴ سال',
          duration: 5,
          position: 'top',
          animation: 'slide',
        },
        {
          timestamp: 50,
          type: 'quote',
          content: '"پاریس بدون برج ایفل، پاریس نیست"',
          duration: 4,
          position: 'center',
          animation: 'fade',
        },
      ],
      transitionType: 'fade',
    },
  ],
  musicStrategy: {
    type: 'dynamic-multi-track',
    tracks: [
      { sceneId: 1, mood: 'Industrial Dream', intensity: 5, transitionType: 'fade' },
      { sceneId: 2, mood: 'Controversy', intensity: 6, transitionType: 'hard-cut' },
      { sceneId: 3, mood: 'Heavy Industry', intensity: 7, transitionType: 'crossfade', crossfadeDuration: 4 },
      { sceneId: 4, mood: 'Building Upward', intensity: 8, transitionType: 'crossfade', crossfadeDuration: 4 },
      { sceneId: 5, mood: 'Triumphant Victory', intensity: 9, transitionType: 'crossfade', crossfadeDuration: 5 },
      { sceneId: 6, mood: 'Eternal Glory', intensity: 7, transitionType: 'fade' },
    ],
  },
  retentionHooks: {
    progressBar: {
      enabled: true,
      position: 'bottom',
      style: 'time-remaining',
    },
    factCardFrequency: 25,
    chapterTitles: true,
    transitionAnimations: true,
  },
});

/**
 * 8. Story Arc Template
 * مثال: داستان شاه آرتور
 */
export const createStoryArcTemplate = (): LongFormStructure => ({
  genre: LongFormGenre.STORY_ARC,
  totalDuration: 8,
  title: 'افسانه شاه آرتور: شمشیر و جادو',
  description: 'داستان افسانه‌ای پادشاه بریتانیا، شمشیر اکسکالیبر، و شوالیه‌های میز گرد',
  scenes: [
    {
      id: 1,
      title: 'پسر بی‌نام',
      duration: 70,
      pieceCount: 400,
      imagePrompt: 'Young Arthur pulling sword from stone, medieval England, Excalibur legend, destiny moment, cinematic',
      storyBeat: 'پسری یتیم شمشیری از سنگ بیرون می‌کشد',
      musicMood: 'Mysterious Origins',
      factCards: [
        {
          timestamp: 15,
          type: 'quote',
          content: '"هر که این شمشیر را بیرون کشد، پادشاه حق است"',
          duration: 5,
          position: 'center',
          animation: 'fade',
        },
        {
          timestamp: 50,
          type: 'fact',
          content: '⚔️ اکسکالیبر: شمشیر جادویی با قدرت افسانه‌ای',
          duration: 4,
          position: 'top',
          animation: 'slide',
        },
      ],
      transitionType: 'fade',
    },
    {
      id: 2,
      title: 'پادشاه جوان',
      duration: 80,
      pieceCount: 600,
      imagePrompt: 'King Arthur crowned, Camelot castle, knights gathering, medieval coronation, majestic kingdom',
      storyBeat: 'آرتور پادشاه می‌شود و کاملوت را بنا می‌نهد',
      musicMood: 'Royal Triumph',
      factCards: [
        {
          timestamp: 20,
          type: 'fact',
          content: '🏰 کاملوت: پایتخت افسانه‌ای پادشاهی آرتور',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 60,
          type: 'statistic',
          content: '⚔️ مرلین جادوگر: مشاور و محافظ آرتور',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'zoom',
    },
    {
      id: 3,
      title: 'میز گرد',
      duration: 90,
      pieceCount: 700,
      imagePrompt: 'Knights of the Round Table, medieval great hall, chivalry oath, brotherhood, legendary warriors',
      storyBeat: 'شوالیه‌های میز گرد: برادری برابر',
      musicMood: 'Brotherhood Epic',
      factCards: [
        {
          timestamp: 25,
          type: 'fact',
          content: '🛡️ لنسلوت: شجاع‌ترین شوالیه',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 70,
          type: 'quote',
          content: '"در میز گرد، همه برابرند"',
          duration: 4,
          position: 'center',
          animation: 'pop',
        },
      ],
      transitionType: 'fade',
    },
    {
      id: 4,
      title: 'جستجوی جام مقدس',
      duration: 90,
      pieceCount: 800,
      imagePrompt: 'Quest for Holy Grail, knights on adventure, mystical forest, medieval quest, divine light',
      storyBeat: 'جستجوی جام مقدس: مأموریت الهی',
      musicMood: 'Mystical Quest',
      factCards: [
        {
          timestamp: 20,
          type: 'fact',
          content: '🏆 جام مقدس: جامی که قدرت شفا می‌بخشد',
          duration: 5,
          position: 'top',
          animation: 'slide',
        },
        {
          timestamp: 65,
          type: 'question',
          content: '❓ کدام شوالیه جام را خواهد یافت؟',
          duration: 4,
          position: 'center',
          animation: 'pop',
        },
      ],
      transitionType: 'puzzle-wipe',
    },
    {
      id: 5,
      title: 'خیانت',
      duration: 80,
      pieceCount: 600,
      imagePrompt: 'Betrayal at Camelot, Lancelot and Guinevere tragic romance, kingdom falling apart, dark atmosphere',
      storyBeat: 'لنسلوت و گینِوِر: عشقی که پادشاهی را ویران کرد',
      musicMood: 'Tragic Betrayal',
      factCards: [
        {
          timestamp: 15,
          type: 'fact',
          content: '💔 گینِوِر: ملکه‌ای میان دو عشق',
          duration: 5,
          position: 'center',
          animation: 'fade',
        },
        {
          timestamp: 60,
          type: 'quote',
          content: '"حتی بزرگ‌ترین پادشاهی‌ها از درون فرو می‌ریزند"',
          duration: 5,
          position: 'top',
          animation: 'slide',
        },
      ],
      transitionType: 'hard-cut',
    },
    {
      id: 6,
      title: 'نبرد نهایی',
      duration: 90,
      pieceCount: 900,
      imagePrompt: 'Battle of Camlann, Arthur vs Mordred, epic medieval battlefield, tragic final battle, dramatic sky',
      storyBeat: 'نبرد کملان: پدر علیه پسر',
      musicMood: 'Epic Battle',
      factCards: [
        {
          timestamp: 20,
          type: 'fact',
          content: '⚔️ موردرد: پسر خائن آرتور',
          duration: 4,
          position: 'top',
          animation: 'fade',
        },
        {
          timestamp: 70,
          type: 'statistic',
          content: '💀 هر دو در نبرد کشته می‌شوند',
          duration: 5,
          position: 'center',
          animation: 'pop',
        },
      ],
      transitionType: 'fade',
    },
    {
      id: 7,
      title: 'افسانه جاودان',
      duration: 70,
      pieceCount: 500,
      imagePrompt: 'Lady of the Lake retrieving Excalibur, mystical Avalon, Arthur immortal legend, magical farewell',
      storyBeat: 'آرتور به آوالون می‌رود، اما افسانه باقی می‌ماند',
      musicMood: 'Eternal Legend',
      factCards: [
        {
          timestamp: 15,
          type: 'quote',
          content: '"پادشاهی که بود و خواهد بود"',
          duration: 5,
          position: 'center',
          animation: 'fade',
        },
        {
          timestamp: 50,
          type: 'fact',
          content: '🗡️ اکسکالیبر به دریاچه بازگردانده شد',
          duration: 4,
          position: 'bottom',
          animation: 'slide',
        },
      ],
      transitionType: 'fade',
    },
  ],
  musicStrategy: {
    type: 'dynamic-multi-track',
    tracks: [
      { sceneId: 1, mood: 'Mysterious Origins', intensity: 5, transitionType: 'fade' },
      { sceneId: 2, mood: 'Royal Triumph', intensity: 7, transitionType: 'crossfade', crossfadeDuration: 5 },
      { sceneId: 3, mood: 'Brotherhood Epic', intensity: 8, transitionType: 'crossfade', crossfadeDuration: 4 },
      { sceneId: 4, mood: 'Mystical Quest', intensity: 6, transitionType: 'crossfade', crossfadeDuration: 5 },
      { sceneId: 5, mood: 'Tragic Betrayal', intensity: 5, transitionType: 'hard-cut' },
      { sceneId: 6, mood: 'Epic Battle', intensity: 10, transitionType: 'crossfade', crossfadeDuration: 4 },
      { sceneId: 7, mood: 'Eternal Legend', intensity: 6, transitionType: 'fade' },
    ],
  },
  retentionHooks: {
    progressBar: {
      enabled: true,
      position: 'bottom',
      style: 'chapter-count',
    },
    factCardFrequency: 30,
    chapterTitles: true,
    transitionAnimations: true,
  },
});

// Export all templates as a map for easy access
export const LONGFORM_TEMPLATES = {
  [LongFormGenre.HISTORICAL_RECONSTRUCTION]: createHistoricalReconstructionTemplate,
  [LongFormGenre.SCIENTIFIC_DEEPDIVE]: createScientificDeepdiveTemplate,
  [LongFormGenre.MYSTERY_REVEAL]: createMysteryRevealTemplate,
  [LongFormGenre.GEOGRAPHIC_JOURNEY]: createGeographicJourneyTemplate,
  [LongFormGenre.ART_EVOLUTION]: createArtEvolutionTemplate,
  [LongFormGenre.LIFE_CYCLE_STORY]: createLifeCycleStoryTemplate,
  [LongFormGenre.CONSTRUCTION_TIMELAPSE]: createConstructionTimelapseTemplate,
  [LongFormGenre.STORY_ARC]: createStoryArcTemplate,
};
